### ISSUE TITLE
CMake Deprecation Warnings and Invalid Target Errors During Build

### ISSUE THREAD

**Issue by BeNavon** [felixokolo/go2_gait_planner#1]
Hello,
I encountered issues while building the `go2_gait_planner` package using colcon build: 'colcon build --packages-select go2_gait_planner'. The build process results in multiple CMake deprecation warnings related to `rosidl_target_interfaces() `and an error indicating an invalid target. Here are the details:

1. The warnings suggest replacing `rosidl_target_interfaces()` with `rosidl_get_typesupport_target()` and `target_link_libraries()`. Example warnings include:
`CMake Deprecation Warning at /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:32 (message):
  Use rosidl_get_typesupport_target() and target_link_libraries() instead of
  rosidl_target_interfaces()
Call Stack (most recent call first):
  CMakeLists.txt:95 (rosidl_target_interfaces)`
2. Additionally, I received the following error:
`CMake Error at /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:38 (message):
  rosidl_target_interfaces() the first argument 'go2_gait_planner_test_node'
  must be a valid target name
Call Stack (most recent call first):
  CMakeLists.txt:100 (rosidl_target_interfaces)`
  
Any help or additional documentation on addressing these issues would be greatly appreciated.
Thank you!

**Comment by felixokolo** [comment]
Check out the new ros2_humble branch. These problems has been addressed in the new branch.

**Comment by BeNavon** [comment]
Thanks! I still get the following error:
`CMake Deprecation Warning at /opt/ros/humble/share/rosidl_cmake/cmake/rosidl_target_interfaces.cmake:32 (message):
  Use rosidl_get_typesupport_target() and target_link_libraries() instead of
  rosidl_target_interfaces()
Call Stack (most recent call first):
  CMakeLists.txt:86 (rosidl_target_interfaces)`
`/home/bennavon/Unitree/go2_gait_planner/src/Low_level/LegMover.cpp: In member function ‘void LegMover::moveLegStraight(Eigen::Vector3d, int, int)’:
/home/bennavon/Unitree/go2_gait_planner/src/Low_level/LegMover.cpp:17:77: warning: unused parameter ‘phaseOffset’ [-Wunused-parameter]
   17 | void LegMover::moveLegStraight(Eigen::Vector3d direction, int duration, int phaseOffset)
      |                                                                         ~~~~^~~~~~~~~~~` 
![Screenshot from 2024-11-12 10-40-52](https://github.com/user-attachments/assets/3f6e0167-e361-4198-8659-9b7f3f21f880)

**Comment by felixokolo** [comment]
The package was successfully built.Those are just warnings. So I will close this issue now. Thanks for the issue.
